// <auto-generated />
namespace EasyQuizy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_groups_and_students : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_groups_and_students));
        
        string IMigrationMetadata.Id
        {
            get { return "201706010815380_add_groups_and_students"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
