// <auto-generated />
namespace EasyQuizy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_formedQuiz_manytomany_with_questions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_formedQuiz_manytomany_with_questions));
        
        string IMigrationMetadata.Id
        {
            get { return "201705300907256_add_formedQuiz_manytomany_with_questions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
